INSERT INTO co203478.BOOK_GENRE (Book_ID, Genre_ID)
VALUES
(61, 1), -- To Kill a Mockingbird (Fiction)
(61, 4), -- To Kill a Mockingbird (Classics)
(62, 1), -- 1984 (Fiction)
(62, 2), -- 1984 (Science Fiction)
(63, 1), -- The Great Gatsby (Fiction)
(63, 4), -- The Great Gatsby (Classics)
(64, 4), -- Pride and Prejudice (Classics)
(64, 7), -- Pride and Prejudice (Romance)
(65, 4), -- The Catcher in the Rye (Classics)
(66, 1), -- Moby Dick (Fiction)
(67, 2), -- Brave New World (Science Fiction)
(67, 4), -- Brave New World (Classics)
(68, 4), -- Wuthering Heights (Classics)
(68, 7), -- Wuthering Heights (Romance)
(69, 4), -- Jane Eyre (Classics)
(69, 7), -- Jane Eyre (Romance)
(70, 3), -- The Hobbit (Fantasy)
(70, 4), -- The Hobbit (Classics)
(71, 2), -- Fahrenheit 451 (Science Fiction)
(71, 4), -- Fahrenheit 451 (Classics)
(72, 2), -- Animal Farm (Science Fiction)
(72, 4), -- Animal Farm (Classics)
(73, 1), -- The Alchemist (Fiction)
(74, 8), -- The Kite Runner (Young Adult)
(75, 3), -- Harry Potter and the Sorcerer''s Stone (Fantasy)
(75, 8), -- Harry Potter and the Sorcerer''s Stone (Young Adult)
(76, 5), -- The Da Vinci Code (Mystery)
(76, 10), -- The Da Vinci Code (Thriller)
(77, 6), -- The Road (Historical Fiction)
(78, 8), -- The Hunger Games (Young Adult)
(78, 10), -- The Hunger Games (Thriller)
(79, 8), -- The Fault in Our Stars (Young Adult)
(79, 7), -- The Fault in Our Stars (Romance)
(80, 1), -- Life of Pi (Fiction)
(80, 6), -- Life of Pi (Historical Fiction)
(81, 1), -- The Book Thief (Fiction)
(81, 6), -- The Book Thief (Historical Fiction)
(82, 9), -- The Shining (Horror)
(83, 3), -- A Game of Thrones (Fantasy)
(84, 6), -- The Help (Historical Fiction)
(85, 10); -- Gone Girl (Thriller)
