SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[BOOK_GENRE](
	[Book_ID] [int] NOT NULL,
	[Genre_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[BOOK_GENRE] ADD PRIMARY KEY CLUSTERED 
(
	[Book_ID] ASC,
	[Genre_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[BOOK_GENRE]  WITH CHECK ADD  CONSTRAINT [FK_BookGenre_Book] FOREIGN KEY([Book_ID])
REFERENCES [co203478].[BOOK] ([Book_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[BOOK_GENRE] CHECK CONSTRAINT [FK_BookGenre_Book]
GO
ALTER TABLE [co203478].[BOOK_GENRE]  WITH CHECK ADD  CONSTRAINT [FK_BookGenre_Genre] FOREIGN KEY([Genre_ID])
REFERENCES [co203478].[GENRE] ([Genre_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[BOOK_GENRE] CHECK CONSTRAINT [FK_BookGenre_Genre]
GO
