SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[BOOKSHELF](
	[Bookshelf_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[Shelf_Name] [nvarchar](255) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[BOOKSHELF] ADD PRIMARY KEY CLUSTERED 
(
	[Bookshelf_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[BOOKSHELF]  WITH CHECK ADD  CONSTRAINT [FK_Bookshelf_User] FOREIGN KEY([User_ID])
REFERENCES [co203478].[USER] ([User_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[BOOKSHELF] CHECK CONSTRAINT [FK_Bookshelf_User]
GO
