SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[GOALS](
	[Goal_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[Start_Date] [date] NOT NULL,
	[Complete_By_Date] [date] NOT NULL,
	[Goal_Type] [nvarchar](50) NOT NULL,
	[Books_Target] [int] NOT NULL,
	[Books_Completed] [int] NULL,
	[Is_Completed] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[GOALS] ADD PRIMARY KEY CLUSTERED 
(
	[Goal_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[GOALS] ADD  DEFAULT ((0)) FOR [Books_Completed]
GO
ALTER TABLE [co203478].[GOALS] ADD  DEFAULT ((0)) FOR [Is_Completed]
GO
ALTER TABLE [co203478].[GOALS]  WITH CHECK ADD  CONSTRAINT [FK_Goals_User] FOREIGN KEY([User_ID])
REFERENCES [co203478].[USER] ([User_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[GOALS] CHECK CONSTRAINT [FK_Goals_User]
GO
