SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[LIBRARY](
	[Library_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[LIBRARY] ADD PRIMARY KEY CLUSTERED 
(
	[Library_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[LIBRARY] ADD UNIQUE NONCLUSTERED 
(
	[User_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[LIBRARY]  WITH CHECK ADD  CONSTRAINT [FK_User_Library] FOREIGN KEY([User_ID])
REFERENCES [co203478].[USER] ([User_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[LIBRARY] CHECK CONSTRAINT [FK_User_Library]
GO
