SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[LIBRARY_BOOK](
	[Library_ID] [int] NOT NULL,
	[Book_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[LIBRARY_BOOK] ADD PRIMARY KEY CLUSTERED 
(
	[Library_ID] ASC,
	[Book_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[LIBRARY_BOOK]  WITH CHECK ADD  CONSTRAINT [FK_LibraryBook_Book] FOREIGN KEY([Book_ID])
REFERENCES [co203478].[BOOK] ([Book_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[LIBRARY_BOOK] CHECK CONSTRAINT [FK_LibraryBook_Book]
GO
ALTER TABLE [co203478].[LIBRARY_BOOK]  WITH CHECK ADD  CONSTRAINT [FK_LibraryBook_Library] FOREIGN KEY([Library_ID])
REFERENCES [co203478].[LIBRARY] ([Library_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[LIBRARY_BOOK] CHECK CONSTRAINT [FK_LibraryBook_Library]
GO
ALTER TABLE co203478.LIBRARY_BOOK
ADD Book_Status NVARCHAR(50);
