SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[MEMBERSHIP](
	[Membership_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[Start_Date] [date] NOT NULL,
	[End_Date] [date] NULL,
	[Price] [decimal](10, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[MEMBERSHIP] ADD PRIMARY KEY CLUSTERED 
(
	[Membership_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[MEMBERSHIP] ADD UNIQUE NONCLUSTERED 
(
	[User_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[MEMBERSHIP]  WITH CHECK ADD  CONSTRAINT [FK_User_Membership] FOREIGN KEY([User_ID])
REFERENCES [co203478].[USER] ([User_ID])
GO
ALTER TABLE [co203478].[MEMBERSHIP] CHECK CONSTRAINT [FK_User_Membership]
GO
