SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[REVIEWS](
	[Review_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[Book_ID] [int] NOT NULL,
	[Review_Date] [date] NOT NULL,
	[Review_Text] [nvarchar](max) NOT NULL,
	[Five_Star_Scale_Rating] [int] NULL,
	[Spoiler_Warning] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [co203478].[REVIEWS] ADD PRIMARY KEY CLUSTERED 
(
	[Review_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[REVIEWS] ADD  DEFAULT ((0)) FOR [Spoiler_Warning]
GO
ALTER TABLE [co203478].[REVIEWS]  WITH CHECK ADD  CONSTRAINT [FK_Review_Book] FOREIGN KEY([Book_ID])
REFERENCES [co203478].[BOOK] ([Book_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[REVIEWS] CHECK CONSTRAINT [FK_Review_Book]
GO
ALTER TABLE [co203478].[REVIEWS]  WITH CHECK ADD  CONSTRAINT [FK_Review_User] FOREIGN KEY([User_ID])
REFERENCES [co203478].[USER] ([User_ID])
ON DELETE CASCADE
GO
ALTER TABLE [co203478].[REVIEWS] CHECK CONSTRAINT [FK_Review_User]
GO
ALTER TABLE [co203478].[REVIEWS]  WITH CHECK ADD CHECK  (([Five_Star_Scale_Rating]>=(1) AND [Five_Star_Scale_Rating]<=(5)))
GO
