SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [co203478].[USER_FOLLOWS](
	[Follower_ID] [int] NOT NULL,
	[Followee_ID] [int] NOT NULL,
	[Follow_Date] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [co203478].[USER_FOLLOWS] ADD  CONSTRAINT [PK_UserFollows] PRIMARY KEY CLUSTERED 
(
	[Follower_ID] ASC,
	[Followee_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [co203478].[USER_FOLLOWS] ADD  DEFAULT (getdate()) FOR [Follow_Date]
GO
ALTER TABLE [co203478].[USER_FOLLOWS]  WITH CHECK ADD  CONSTRAINT [FK_UserFollows_Followee] FOREIGN KEY([Followee_ID])
REFERENCES [co203478].[USER] ([User_ID])
GO
ALTER TABLE [co203478].[USER_FOLLOWS] CHECK CONSTRAINT [FK_UserFollows_Followee]
GO
ALTER TABLE [co203478].[USER_FOLLOWS]  WITH CHECK ADD  CONSTRAINT [FK_UserFollows_Follower] FOREIGN KEY([Follower_ID])
REFERENCES [co203478].[USER] ([User_ID])
GO
ALTER TABLE [co203478].[USER_FOLLOWS] CHECK CONSTRAINT [FK_UserFollows_Follower]
GO
